@api = http://localhost:4000/api/auth

###
POST {{api}}/sign-up
Content-Type: application/json

{
    "username": "user2@gmail.com",
    "email": "hola2@gmail.com",
    "password": "claudio123"
}
###
POST {{api}}/sign-in